web3/src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Idea::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $idea;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="datetime")
     */
    private $pub_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdea(): ?Idea
    {
        return $this->idea;
    }

    public function setIdea(?Idea $idea): self
    {
        $this->idea = $idea;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getPubDate(): ?\DateTimeInterface
    {
        return $this->pub_date;
    }

    public function setPubDate(\DateTimeInterface $pub_date): self
    {
        $this->pub_date = $pub_date;

        return $this;
    }
}

web3/src/Form/CommentType.php
<?php

namespace App\Form;

use App\Entity\Comment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('text',TextareaType::class,[
                'label'=>false,
                'attr'=>[
                    'placeholder'=>'Your comment here'
                ]
            ])
        //    ->add('pub_date')
        //    ->add('idea')
        //    ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Comment::class,
        ]);
    }
}

web3/src/Controller/CommentController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Idea;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/comment")
 */
class CommentController extends Controller
{
    /**
     * @Route("/", name="comment_index", methods={"GET"})
     */
    public function index(CommentRepository $commentRepository): Response
    {
        return $this->render('comment/index.html.twig', [
            'comments' => $commentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new/{idea}", name="comment_new", methods={"GET","POST"})
     */
    public function new(Request $request, Idea $idea): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        $user = $this->container->get('security.token_storage')->getToken()->getUser();
        if ($form->isSubmitted() && $form->isValid() && $user) {
            $entityManager = $this->getDoctrine()->getManager();
            $comment->setIdea($idea);
            $comment->setPubDate(new DateTime());
            $comment->setUser($user);
            $entityManager->persist($comment);
            $entityManager->flush();
            return $this->redirectToRoute('idea_show',[ 'id'=>$idea->getId() ]);
        }

        return $this->render('comment/new.html.twig', [
            'comment' => $comment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="comment_show", methods={"GET"})
     */
    public function show(Comment $comment): Response
    {
        return $this->render('comment/show.html.twig', [
            'comment' => $comment,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="comment_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Comment $comment): Response
    {
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('comment_index');
        }

        return $this->render('comment/edit.html.twig', [
            'comment' => $comment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="comment_delete", methods={"DELETE","POST"})
     */
    public function delete(Request $request, Comment $comment): Response
    {
        if ($this->isCsrfTokenValid('delete'.$comment->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($comment);
            $entityManager->flush();
            return $this->json(array(
                'status' => 'success'
            ));
        }

        return $this->json(array(
            'status' => 'error'
        ),400);
    }
}

web3/templates/comment/_delete_form.html.twig
<form method="post" action="{{ path('comment_delete', {'id': comment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
    <button class="btn">Delete</button>
</form>

web3/templates/comment/_form.html.twig
{% set comment_form=comment_forms[idea.id] %}
{{ form_start(comment_form, {'action': path('comment_new', {idea:idea.id} ), 'name':'comment_idea_'~idea.id,'attr': { 'id': 'comment_idea_'~idea.id  } }) }}
    {{ form_widget(comment_form) }}
    <button class="btn btn-primary">{{ button_label|default('Save Comment') }}</button>
{{ form_end(comment_form) }}

web3/templates/comment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Comment{% endblock %}

{% block body %}
    <h1>Edit Comment</h1>
    {{ include('comment/_form.html.twig', {'button_label': 'Update'}) }}
    <a href="{{ path('comment_index') }}">back to list</a>
    {{ include('comment/_delete_form.html.twig') }}
{% endblock %}

web3/templates/comment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comment index{% endblock %}

{% block body %}
    <h1>Comment index</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Text</th>
                <th>Pub_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for comment in comments %}
            <tr>
                <td>{{ comment.id }}</td>
                <td>{{ comment.text }}</td>
                <td>{{ comment.pubDate ? comment.pubDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('comment_show', {'id': comment.id}) }}">show</a>
                    <a href="{{ path('comment_edit', {'id': comment.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('comment_new') }}">Create new</a>
{% endblock %}

web3/templates/comment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Comment{% endblock %}

{% block body %}
    <a href="{{ path('comment_index') }}">back to list</a>
    <h1>Create new Comment</h1>

    {{ include('comment/_form.html.twig') }}

{% endblock %}

web3/templates/comment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comment{% endblock %}

{% block body %}
    <h1>Comment</h1>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ comment.id }}</td>
            </tr>
            <tr>
                <th>Text</th>
                <td>{{ comment.text }}</td>
            </tr>
            <tr>
                <th>Pub_date</th>
                <td>{{ comment.pubDate ? comment.pubDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('comment_index') }}">back to list</a>

    <a href="{{ path('comment_edit', {'id': comment.id}) }}">edit</a>

    {{ include('comment/_delete_form.html.twig') }}
{% endblock %}